### ISSUE TITLE
start slumen occur error with ubuntu18,php72,swoole4.3,lumen5.8

### ISSUE THREAD

**Issue by kindywu** [breeze2/slumen#1]
kindy@ubuntu64:/mnt/hgfs/assembly$ vendor/bin/slumen start
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Dotenv\Dotenv::__construct() must be an instance of Dotenv\Loader, string given, called in /mnt/hgfs/assembly/bootstrap/slumen.php on line 6 and defined in /mnt/hgfs/assembly/vendor/vlucas/phpdotenv/src/Dotenv.php:31
Stack trace:
#0 /mnt/hgfs/assembly/bootstrap/slumen.php(6): Dotenv\Dotenv->__construct('/mnt/hgfs/assem...')
#1 /mnt/hgfs/assembly/vendor/breeze2/slumen/src/Command.php(18): require('/mnt/hgfs/assem...')
#2 /mnt/hgfs/assembly/vendor/breeze2/slumen/src/Command.php(169): BL\Slumen\Command->__construct()
#3 /mnt/hgfs/assembly/vendor/breeze2/slumen/bin/slumen(30): BL\Slumen\Command::main(Array)
#4 {main}
  thrown in /mnt/hgfs/assembly/vendor/vlucas/phpdotenv/src/Dotenv.php on line 31

**Comment by breeze2** [comment]
For Lumen 5.8, please modify the file `PROJECT_PATH/bootstrap/slumen.php`.

Replace
```php
<?php
...
try {
    (new Dotenv\Dotenv(__DIR__ . '/../'))->load();
} catch (Dotenv\Exception\InvalidPathException $e) {
    //
}
...
```

with
```php
<?php
...
(new Laravel\Lumen\Bootstrap\LoadEnvironmentVariables(
    dirname(__DIR__)
))->bootstrap();
...
```

**Comment by kindywu** [comment]
thank，this problem will be resolve in next release ?

**Comment by breeze2** [comment]
Maybe your `PROJECT_PATH/bootstrap/slumen.php` is copied from the `PROJECT_PATH/vendor/breeze2/slumen/bootstrap/slumen.php`, but it is just a sample file.

The `PROJECT_PATH/bootstrap/slumen.php` is under your control, please code it like coding the `PROJECT_PATH/bootstrap/app.php`.

**Comment by breeze2** [comment]
The `bootstrap/slumen58.php` is in slumen v1.3.0 now.
