### ISSUE TITLE
两个连接池的区别是什么？

### ISSUE THREAD

**Issue by robbinhan** [breeze2/slumen#3]
`BL\Slumen\Runtime\MySqlConnectionPool`和`BL\Slumen\Coroutine\MySqlConnectionPool`两种连接池的方式

1.主要区别是什么？
2.各自的使用场景是什么？

**Comment by breeze2** [comment]
[Coroutine](https://wiki.swoole.com/wiki/page/p-coroutine.html)和[Runtime](https://wiki.swoole.com/wiki/page/p-runtime.html)是Swoole提供的两个特性：

- [Coroutine\MySQL](https://wiki.swoole.com/wiki/page/p-coroutine_mysql.html)是Swoole基于Coroutine（仿golang）实现的一个异步MySQL客户端；
- Runtime\MySQL本身就是原来的PDO或mysqli，只不过底层替换了ZendVM Stream的函数指针，原来的一些同步阻塞操作变成来协程调度的异步IO。

**Comment by robbinhan** [comment]
谢谢说明
